from .minimum import Minimum
from .aircraft import Aircraft
from .user import User
from .student import Student
from .exercise import Exercise
from .flight import Flight
from .exercise_meteo import ExerciseMeteo
from .crew_exercise import CrewExercise
from .crew_members_flight_time import CrewMembersFlightTime
from .flight_exercise_report import FlightExerciseReport
from .flight_exercise import FlightsExercise
from .shift_item import ShiftItem
from .shift import Shift